# action.yaml
name: 'Massdriver Kubernetes CD'
description: 'Consumes a Massdriver kubernetes-cluster artifact, and deploys a new version of a specified application to the cluster.'
runs:
  using: 'docker'
  image: 'Dockerfile'
