name: Deploy to staging
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        id: ecr-Login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            latest=true
          images: <account-id>.dkr.ecr.us-west-2.amazonaws.com/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha
      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy_application:
    name: Deploy
    runs-on: ubuntu-latest
    # waits for the image to be build and pushed to ECR
    needs: build_and_push
    steps:
      - name: Deploy the application
        uses: massdriver-cloud/kubernetes-deploy-github-action@v1.1.0
        env:
          ARTIFACT_KUBERNETES_CLUSTER: ${{ secrets.ARTIFACT_KUBERNETES_CLUSTER_STAGING }}
          APPLICATION_NAME: infra-staging-myapp-884422
          IMAGE: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/<organization>/<application>:${{ github.sha }}
